name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Linting & Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run Tests
        run: |
          coverage run --source='.' manage.py test
          coverage report -m

      - name: Check test coverage
        run: |
          coverage_percent=$(coverage report | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
          if (( $(echo "$coverage_percent < 80" | bc -l) )); then
            echo "Test coverage is below 80%. Exiting."
            exit 1
          fi

  build_and_push:
    name: "Build & Push Docker Image"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && echo "Docker login successful"

      - name: Build Docker Image
        run: |
          docker build -t oc_lettings_site:latest .
          docker tag oc_lettings_site:latest "${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:latest"
          docker tag oc_lettings_site:latest "${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:${{ github.sha }}"

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:latest"
          docker push "${{ secrets.DOCKER_USERNAME }}/oc_lettings_site:${{ github.sha }}"

  deploy:
    name: "Deploy to Render"
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
